---
- include: ../local-setup.yaml

- hosts: $hosts
  user: $user
  gather_facts: false
  vars_files:
    - ../local-setup-vars.yaml
  tasks:
    - name: Run Homebrew install script
      command: ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"