---

- hosts: localhost
{{ list1 | union(list2) }}
  tasks:

    - debug: msg="** macSetup RSync Daemon module **"

    - name: Update Brew and RSync
      homebrew: update_homebrew=yes upgrade_all=yes
    - homebrew: update_homebrew=yes upgrade_all=yes
    - shell: brew cleanup
    - homebrew_tap: name="homebrew/dupes" state=present
    - homebrew: name="rsync" state=present

    - name: Copy configuration files
      copy: src='{{ item.src }}' dest='{{ item.dest }}' mode='{{ item.mode }}'
      with_items:
       - src: "org.samba.rsync.plist"
         dest: "/Library/LaunchDaemons/"
         mode: 0644
       - src: "rsyncd.conf"
         dest: "/etc/"
         mode: 0644
       - src: "rsyncd.secrets"
         dest: "/etc/"
         mode: 0600
      become: yes

    - name: Launch the daemon
      command: "launchctl load /Library/LaunchDaemons/org.samba.rsync.plist"
      become: yes

