---
# ------------------------------------------------------------
# Backup my environment and package configurations
# Modified by: Benoît H. Dicaire
# https://GitHub.com/bhdicaire/macSetup
# ------------------------------------------------------------

- hosts:      localhost
  connection: local
  vars:
    macBackupConfig: false
    macBackupRestore: false

  pre_tasks:
   - name: Load all variables and dictionaries
     include_tasks: "roles/prepareMac/tasks/loadAllVariables.yml"  

   - name: Dump all variables and dictionaries
     include_tasks: "roles/common/tasks/dumpAllVariables.yml"  
     vars: 
       dDumpFile:   "/tmp/debugAllVariables(before).txt" 

  tasks:  
#   - name: Execute debug tasks
#     command: "osascript -e 'tell application \"System Events\" to make login item at end with properties \{path: \"/Applications/Safari.app\", hidden:false\}'"

   - name: Backup - Copy configuration items
     block: 
       - include_tasks: "{{ playbookPath }}/roles/common/tasks/cpItems.yml"
         vars:
           dCopyItem:
             src:  "{{ item.src }}{{ item.suffix }}"
             dest: "{{ item.dest }}"
           dMkDir: false
         with_items:
           - "{{ secretConfigurationItems }}"
#          - "{{ dotFilesItems }}"
#           - "{{ macSoftwareConfig }}"  
#           - "{{ systemRelatedItems }}"

  post_tasks:
   - name: Dump all variables and dictionaries
     include_tasks: "roles/common/tasks/dumpAllVariables.yml"    
     vars: 
       dDumpFile: "/tmp/debugAllVariables(after).txt" 
#
#function add_login_item {
#	osascript -e "tell application \"System Events\" to make login item at end with properties {path: \"$1\", hidden:true}"
#}
#
#add_login_item "/Applications/iTerm.app"
#add_login_item "/Applications/Safari.app"