---
# ------------------------------------------------------------
# macSetup according to my opinionated standards
# Modified by: Benoît H. Dicaire
# https://GitHub.com/bhdicaire/macSetup
# ------------------------------------------------------------

- hosts:      localhost
  connection: local
  vars_prompt:
   - name: "ansible_become_pass"
     prompt: "Sudo password"
     private: yes

  pre_tasks:
#    - name: "Load global variables and dictionaries"
#      ansible.builtin.include_vars:
#        dir: '{{ playbook_dir }}/config/'
#        ignore_unknown_extensions: True
#        extensions:
#          - 'yml'

   - name: "debug: dump all variables and dictionaries"
     import_tasks: "roles/provision/tasks/debug.yml"
     when: goougou is defined

   - name: 'Helllo'
     ansible.builtin.shell: "echo {{ item }}"
     with_items:
       -  "{{ userPreferences.uxDockComponents }}"
     when: goougou is defined

  roles:
   - { role: provision}

#   post_tasks:
#    - name: Dump all variables and dictionaries
#      include_tasks: "roles/common/tasks/dumpAllVariables.yml"
#      vars:
#        dDumpFile: "/tmp/dumpAllVariables (provisionMac completed).txt"
#      when: debugAnsible is defined
