---
# ------------------------------------------------------------
# Prepare my computer environment to backup / restore my configuration
# Modified by: Benoît H. Dicaire
# https://GitHub.com/bhdicaire/macSetup
# ------------------------------------------------------------

    - debug: var=inventory_hostname
    - debug: 
        msg: "** macSetup - Prepare computer environment }} **"
        verbosity: 2
            
    - name: Setup module marker 
      file: path="~/.macSetup-env" state=touch owner="{{ localUser }}"

    - name: Execute mkDir module
      include_tasks: "{{ playbookPath }}/roles/common/tasks/mkDir.yml"
      vars:
        dDirPath: "{{ dMake }}"
        dDirGroup: "Staff"
      with_items:
        - "~/BCK/BusyCal/"
        - "~/BCK/BusyContact/"
      loop_control:
        loop_var: dMake
      when: dMkDir == True  
      
    - name: Execute mkDir module2
      include_tasks: "{{ playbookPath }}/roles/common/tasks/mkDir.yml"
      vars:
        dDirPath: "{{ dMake }}"
        dDirGroup: "Staff"
      with_items:
        - "{{ brewCaskConfig.dest }}"
        - "{{ macSoftwareConfig.src }}"
        - "{{ macSoftwareURL.dest }}"
        - "{{ toolsPath }}"
      loop_control:
        loop_var: dMake
      when: dMkDir == True 
         
    - name: Setup module marker 
      file: path="~/.macSetup-env" state=absent  