---
# ------------------------------------------------------------
# Prepare my computer environment to backup / restore my configuration
# Modified by: Benoît H. Dicaire
# https://GitHub.com/bhdicaire/macSetup
# ------------------------------------------------------------

- debug: var=inventory_hostname
- debug: 
    msg: "** macSetup - Prepare computer environment **"
    verbosity: 2
        
- name: Setup module marker 
  file: path="~/macSetup-backupDir" state=touch owner="{{ localUser }}"

- include_tasks: "{{ playbookPath }}/roles/common/tasks/loadAllVariables.yml"

- include_tasks: "{{ playbookPath }}/roles/common/tasks/dumpAllVariables.yml"

- include_tasks: "{{ playbookPath }}/roles/common/tasks/mkDir.yml"
  vars:
    dDirPath: "{{ dMake }}"
    dDirGroup: "Staff"
  with_items:
    - "{{ backupPath }}"
    - "{{ toolsPath }}"
    - "{{ spotlightPath}}"
    - "{{ gitPath }}"
    - "{{ macSetupLocalGIT }}"
    - "{{ dotFilesLocalGIT }}"
    - "{{ dotFilesPath }}"
    - "{{ toolsPath }}"
    - "{{ secretBackupPath }}"
    - "{{ backupPath + dotFilesItems.0.dest }}"
    - "{{ secretBackupPath + secretConfigurationItems.0.dest }}"
    - "{{ backupPath }}BusyCal/"
    - "{{ backupPath }}BusyContact/"
  loop_control:
    loop_var: dMake

- include_tasks: "{{ playbookPath }}/roles/common/tasks/mkDir.yml"
  vars:
    dDirPath: "{{ dMake.dest }}"
    dDirGroup: "Staff"
  with_items:
    - "{{ macSoftwareConfig }}"
    - "{{ systemRelatedGITItems }}"
    - "{{ brewCaskConfig }}" 
  loop_control:
    loop_var: dMake

- name: Remove module marker 
  file: path="~/macSetup-backupDir" state=absent  