
# ------------------------------------------------------------
# Generic items
# ------------------------------------------------------------

    home: "{{ lookup('env','HOME') }}"
    localUser: "{{ lookup('env','USER') }}"
    localID: "{{ ansible_effective_user_id}}"
    localGID: "{{ ansible_effective_group_id }}"
    playbookPath: "{{ playbook_dir }}"
    computerCPU : "{{ ansible_processor }}"
    computerCPUArchitecture: "{{ ansible_userspace_architecture }}"
    computerCores: "{{ ansible_processor_cores }}"
    brewPrefixes:
      x86_64: /usr/local
      arm64: /opt/homebrew
    brewPrefix: "{{ brewPrefixes[ansible_machine] }}"
    brewDir:    "{{ brewPrefix }}/bin"
    spotlightPath: "~/Library/Spotlight/"
