# ------------------------------------------------------------
# macSetup according to my opinionated standards
# Modified by: Benoît H. Dicaire
# https://GitHub.com/bhdicaire/macSetup
# ------------------------------------------------------------

    debugAnsible: true

    macSetup: true
    macDevSetup: false
    macServerSetup: false
      
    computerName: "dogbert"

# ------------------------------------------------------------
# Generic items
# ------------------------------------------------------------

    home: "{{ lookup('env','HOME') }}"
    localUser: "{{ lookup('env','USER') }}"
    localID: "{{ ansible_effective_user_id}}"
    localGID: "{{ ansible_effective_group_id }}"
    playbookPath: "{{ playbook_dir }}"
    computerCPU : "{{ ansible_processor }}"
    computerCPUArchitecture: "{{ ansible_userspace_architecture }}"
    computerCores: "{{ ansible_processor_cores }}"
    
    brewDir: "/usr/local/"
    brew_cask_appdir: "/Applications"
    spotlightPath: "~/Library/Spotlight/"

    macSetupPathSuffix: "macSetup/"
    dotFilesPathSuffix: "dotFiles/"

# ------------------------------------------------------------
# Secret items
# ------------------------------------------------------------

    aws_cli_user: "{{ lookup('env','aws_cli_user') }}" 
    aws_cli_group: "{{ lookup('env','aws_cli_group') }}"
    aws_region: "{{ lookup('env','aws_region') }}"
    aws_access_key_id: "{{ lookup('env','aws_access_key_id') }}"
    aws_secret_access_key: "{{ lookup('env','aws_secret_access_key') }}"

# ------------------------------------------------------------
# PLEASE CUSTOMIZE THE FOLLOWING VARIABLES
# ------------------------------------------------------------

    localUserComment: "Benoît H. Dicaire"
    localGroup: "staff"
    localGroups: "admin,staff,DST"
    localShell: "/usr/local/bin/bash"
    
    pathPrefix: "/tmp/"
    dropboxPath: "~/Dropbox/"

    toolsPath: "{{ pathPrefix }}macTools/"
    backupPath: "{{ pathPrefix }}BCK/"
    secretBackupPath: "{{ pathPrefix }}SecretBCK/"
    
    gitPath: "{{ pathPrefix }}GIT/"
    macSetupLocalGIT: "{{ gitPath }}{{ macSetupPathSuffix }}"
    dotFilesLocalGIT: "{{ gitPath }}{{ dotFilesPathSuffix }}"

    macSetupGIT: "https://github.com/bhdicaire/macSetup.git"
    macSetupPath: "{{ pathPrefix }}{{ macSetupPathSuffix }}"
    dotFilesGIT: "https://github.com/bhdicaire/dotFiles.git"
    dotFilesPath: "{{ pathPrefix }}{{ dotFilesPathSuffix }}"

    macSetupRoles:
      - prepareMac
      - deployMac
      - deployDev
      - deployServer

    moreGroups:
      - name: "Friends"
        gid: "999"
      - name: "DST"
        gid: "888"

    moreUsers:
      - name: “bob”
        comment: "Benoît H. Dicaire (admin)"
        group: "staff"
        groups: "admin,DST,Friends"
        shell: "/usr/local/bin/bash"
      - name: “rob”
        groups: "admin,staff,Friends"
        shell: "/usr/local/bin/bash"
