---

userPreferences:

  timeMachine:
    - name: Prevent Time Machine from prompting to use new hard drives as backup volume
      domain: com.apple.TimeMachine
      key: DoNotOfferNewDisksForBackup
      type: bool
      value: true

  timeMachineSystem:
    - name: Changes the backup interval to 30 minutes. The integer value is the time in seconds
      domain: com.apple.backupd-auto
      key: StartInterval
      type: int
      value: 1800

#   cmdSudo:
#     - name: Time Machine performs local backups while the Time Machine backup volume is not available
#       value: "tmutil disablelocal"
#     - name: Verify Backup - Time Machine records checksums of files copied into snapshots
#       value: "tmutil verifychecksums /path/to/backup"
