---

userPreferences:

  photoSystem:
    - name: Prevent Time Machine from prompting to use new hard drives as backup volume
      domain: com.apple.TimeMachine
      key: DoNotOfferNewDisksForBackup
      type: bool
      value: true
    - name: Prevent Photos from opening automatically when devices are plugged in
      domain: com.apple.ImageCapture
      key: disableHotPlug
      type: bool
      value: true
