---
# ------------------------------------------------------------
# Prepare the setup according to my opinionated standards
# Modified by: Benoît H. Dicaire
# https://GitHub.com/bhdicaire/macSetup
# ------------------------------------------------------------
# Collection of useful scripts for doing odd things

# Load variables and dictionaries

 - name: "Load variables and dictionaries"
   include_vars: dir="{{ playbookPath }}/roles/{{ item }}/vars"
   with_items:
     - "{{ macSetupRoles }}"
