---

 activityMonitorPref:

# Show the main window when launching Activity Monitor
    - "com.apple.ActivityMonitor OpenMainWindow -bool true"

# Visualize CPU usage in the Activity Monitor Dock icon
    - "com.apple.ActivityMonitor IconType -int 5"

# Show all processes in Activity Monitor
    - "com.apple.ActivityMonitor ShowCategory -int 0"

# Sort Activity Monitor results by CPU usage
    - "com.apple.ActivityMonitor SortColumn -string 'CPUUsage'"
    - "com.apple.ActivityMonitor SortDirection -int 0"