---

 finderSettings:

# Arrange Files by Kind
    - id: 'Set :DesktopViewSettings:IconViewSettings:arrangeBy kind' 
      bundle: '~/Library/Preferences/com.apple.finder.plist'
    - id: 'Set :StandardViewSettings:IconViewSettings:arrangeBy kind'
      bundle: '~/Library/Preferences/com.apple.finder.plist'
      
# Set the Grid Spacing for Files ...54 and 30 ?
    - id: 'Set :DesktopViewSettings:IconViewSettings:gridSpacing 1'
      bundle: '~/Library/Preferences/com.apple.finder.plist'
    - id: 'Set :StandardViewSettings:IconViewSettings:gridSpacing 1'
      bundle: '~/Library/Preferences/com.apple.finder.plist'

#  Use Smaller Icons
    - id: 'Set :DesktopViewSettings:IconViewSettings:iconSize 48'
      bundle: '~/Library/Preferences/com.apple.finder.plist'
    - id: 'Set :StandardViewSettings:IconViewSettings:iconSize 64'
      bundle: '~/Library/Preferences/com.apple.finder.plist'

# Set icon label text size
    - id: 'Set :DesktopViewSettings:IconViewSettings:textSize 13'
      bundle: '~/Library/Preferences/com.apple.finder.plist'
    - id: 'Set :StandardViewSettings:IconViewSettings:textSize 13'
      bundle: '~/Library/Preferences/com.apple.finder.plist'

# Set icon label position
    - id: 'Set :DesktopViewSettings:IconViewSettings:labelOnBottom true'
      bundle: '~/Library/Preferences/com.apple.finder.plist'
    - id: 'Set :StandardViewSettings:IconViewSettings:labelOnBottom true'
      bundle: '~/Library/Preferences/com.apple.finder.plist'

# Show item info
    - id: 'Set :DesktopViewSettings:IconViewSettings:showItemInfo true'
      bundle: '~/Library/Preferences/com.apple.finder.plist'
    - id: 'Set :StandardViewSettings:IconViewSettings:showItemInfo true'
      bundle: '~/Library/Preferences/com.apple.finder.plist'

# Set sort method
    - id: 'Set :DesktopViewSettings:IconViewSettings:arrangeBy none'
      bundle: '~/Library/Preferences/com.apple.finder.plist'    
    - id: 'Set :StandardViewSettings:IconViewSettings:arrangeBy none'
      bundle: '~/Library/Preferences/com.apple.finder.plist'

 finderItems:
    - "chflags nohidden ~/Library"
    - "open /System/Library/CoreServices/PowerChime.app"

 finderPref:

# Show Drives on the Desktop
    - "com.apple.finder ShowHardDrivesOnDesktop -bool true"

# Avoid creating .DS_Store files on network or USB volumes
    - "com.apple.desktopservices DSDontWriteNetworkStores -bool true"
    - "com.apple.desktopservices DSDontWriteUSBStores -bool true"

# Disable all animations
    - "com.apple.finder DisableAllAnimations -bool true"

# Search the current directory by default
    - "com.apple.finder FXDefaultSearchScope -string 'SCcf'"

# Automatically open a new Finder window when a volume is mounted
    - "com.apple.frameworks.diskimages auto-open-ro-root -bool true"
    - "com.apple.frameworks.diskimages auto-open-rw-root -bool true"
    - "com.apple.finder OpenWindowForNewRemovableDisk -bool true"

# Show External Drives on the Desktop
    - "com.apple.finder ShowExternalHardDrivesOnDesktop -bool true"

# Set Desktop as the default location for new Finder windows
# For other paths, use `PfLo` and `file:///full/path/here/`
    - "com.apple.finder NewWindowTarget -string 'PfDe'"
    - "com.apple.finder NewWindowTargetPath -string 'file://${HOME}/Desktop/'"

# Show icons for hard drives, servers, and removable media on the desktop
    - "com.apple.finder ShowExternalHardDrivesOnDesktop -bool true"
    - "com.apple.finder ShowHardDrivesOnDesktop -bool true"
    - "com.apple.finder ShowMountedServersOnDesktop -bool true"
    - "com.apple.finder ShowRemovableMediaOnDesktop -bool true"

# Show Hidden Files
    - "com.apple.finder AppleShowAllFiles -bool true"

# Show File Extensions
    - "NSGlobalDomain AppleShowAllExtensions -bool true"

# Show the Status Bar in Finder
    - "com.apple.finder ShowStatusBar -bool true"

# Show the Path Bar in Finder
    - "com.apple.finder ShowPathbar -bool true"

# Increase Number of Recent Places
    - "-g NSNavRecentPlacesLimit -int 10"

# Expand the following File Info panes: “General”, “Open with”, and “Sharing & Permissions”
    - "com.apple.finder FXInfoPanesExpanded -dict General -bool true OpenWith -bool true Privileges -bool true"

# Finder allow text selection in Quick Look
    - "com.apple.finder QLEnableTextSelection -bool true"

# Display full POSIX path as Finder window title
    - "com.apple.finder _FXShowPosixPathInTitle -bool true"

# Use list view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
    - "com.apple.finder FXPreferredViewStyle -string 'Nlsv'"

# Disabling the warning when changing a file extension
    - "com.apple.finder FXEnableExtensionChangeWarning -bool false"

# Disable the warning before emptying the Trash
    - "com.apple.finder WarnOnEmptyTrash -bool false"

# Empty Trash securely by default
    - "com.apple.finder EmptyTrashSecurely -bool true"