---

# ------------------------------------------------------------
#  Mac Software — Download DMG, GIT, ISO & PKG
# ------------------------------------------------------------

 macSoftwareURL:

  - name: "ParallelsToolbox"
    app: "Parallels Toolbox.app"
    src: "http://www.parallels.com/ca/try/toolbox"
    dest: "{{ toolsPath }}"
    installer_type: app
    install_method: dmg

  - name: "SetApp"
    app: "Install Setapp.app"
    src: "https://dl.devmate.com/com.setapp.InstallSetapp/InstallSetapp.zip"
    dest: "{{ toolsPath }}"
    installer_type: app
    install_method: zip
# move app dans /Applications


### TODO: Copy antidote via RSync :(
### TODO: find hemingway editor

#  Microsoft Office 2016  —  Mac O365/Retail
#                            https://macadmins.software

# Word,Excel, PowerPoint, Outlook, OneNote & MS AutoUpdate (MAU)
  - src: "https://go.microsoft.com/fwlink/?linkid=525133"
    dest: "{{ toolsPath }}"
# Skype for Business 2016 — https://macadmins.software
  - src: "https://go.microsoft.com/fwlink/?linkid=832978"
    dest: "{{ toolsPath }}"


 macSoftwareGIT:

  - name: O365SharedActivator
    src: "https://github.com/pbowden-msft/O365SharedActivator"
    dest: "{{ toolsPath }}O365SharedActivator"
    installer_type: app
    install_method: git
  - name: NukeOffKeychain
    src: "https://github.com/pbowden-msft/NukeOffKeychain"
    dest: "{{ toolsPath }}MS-NukeOffKeychain"
    installer_type: app
    install_method: git

# ------------------------------------------------------------
#  Brew — CLI Applications
# ------------------------------------------------------------

 brew:
    - rename
    - tree
    - bep/tap/s3deploy
    - awscli
    - azure-cli
    - minio/stable/mc
    - hugo
    - ack
    - exiftool
    - gnupg2
    - go
    - handbrake
    - wget

# ------------------------------------------------------------
#  Brew Cask — GUI Applications
# ------------------------------------------------------------

 brewCask:
    - 1password
    - bartender
    - bbedit
    - busycal
    - dropbox
    - evernote
    - fantastical
    - google-chrome
    - houdahspot
    - istat-menus
    - karabiner-elements
    - keybase
    - neofinder
    - omnifocus
    - omnigraffle
    - omnioutliner
    - omnipresence
    - path-finder
    - pdfpenpro
    - fujitsu-scansnap-manager-ix500
    - sonos
    - superduper
    - switchresx
    - terminology
    - vlc
    - calibre
    - choosy
    - chronosync
    - default-folder-x
    - force-paste
    - hazel
    - makemkv
    - snagit
    - sqlitebrowser
    - suspicious-package
    - zoom
    - zoom-outlook-plugin
    - webex
    - microsoft-teams

# ------------------------------------------------------------
#  Brew Cask — Quicklook modules
# ------------------------------------------------------------

    - betterzipql
    - epubquicklook
    - qlcolorcode
    - qldds
    - qlimagesize
    - qlmarkdown
    - qlprettypatch
    - qlstephen
    - qlvideo
    - quicklook-csv
    - quicklook-json
    - quicklook-pat
    - quicklook-pfm
    - quicklookase
    - receiptquicklook
    - ttscoff-mmd-quicklook
    - webpquicklook

# ------------------------------------------------------------
#  Mac Apps Store —  MAS Applications
# ------------------------------------------------------------

 appStore:
    - id: "409183694"
      name: "Keynote (7.2)"
    - id: "413857545"
      name: "Divvy (1.5.1)"
    - id: "413965349"
      name: "Soulver (2.6.2)"
    - id: "588726889"
      name: "ReadKit (2.5.2)"
    - id: "639764244"
      name: "Xee³ (3.5.2)"
    - id: "824171161"
      name: "Affinity Designer (1.5.5)"
    - id: "918858936"
      name: "Airmail 3 (3.3.2)"
    - id: "964258399"
      name: "BusyContacts (1.1.9)"
    - id: "979561272"
      name: "Just Press Record (1.4.3)"
    - id: "603637384"
      name: "Name Mangler 3 (3.4)"
    - id: "890031187"
      name: "Marked 2 (2.5.10"
    - id: "924726344"
      name: "Deliveries (3.0.3)"
    - id: "409907375"
      name: "Remote Desktop (3.9)"
    - id: "411643860"
      name: "DaisyDisk (4.4)"
    - id: "442168834"
      name: "SiteSucker (2.10.4)"
    - id: "446107677"
    - id: "1090488118"
      name: "Gemini 2 (2.3.6)"
    - id: "1491071483"
      name: "Tot (1.2.1)"
    - id: "1225570693"
      name: "Ulysses (21.6)"
    - id: "462058435"
      name: "Microsoft Excel (16.46)"
    - id: "1193683552"
      name: "VisualDesigner (5.7)"
    - id: "1226444549"
      name: "Phiewer (lite) (3.2.0)"
    - id: "1081457679"
      name: "The Ebook Converter (11.0)"
    - id: "918858936"
      name: "Airmail (5.0.1)"
    - id: "824171161"
      name: "Affinity Designer (1.9.1)"
    - id: "462054704"
      name: "Microsoft Word (16.46)"
    - id: "1439967473"
      name: "Okta Extension App (5.43.0)"
    - id: "924726344"
      name: "Deliveries (3.2.3)"
    - id: "1044484672"
      name: "ApolloOne (2.9.4)"
    - id: "441258766"
      name: "Magnet (2.5.0)"
    - id: "442168834"
      name: "SiteSucker (3.2.3)"
    - id: "462062816"
      name: "Microsoft PowerPoint (16.46)"
    - id: "402569179"
      name: "Find Any File (2.2.1)"
    - id: "1295203466"
      name: "Microsoft Remote Desktop (10.5.2)"
      name: "Slack (4.13.0)"
    - id: "784801555"
      name: "Microsoft OneNote (16.46)"
    - id: "985367838"
      name: "Microsoft Outlook (16.46)"
    - id: "405399194"
      name: "Kindle (1.30.0)"
    - id: "935235287"
      name: "Encrypto (1.3.7)"
    - id: "409203825"
      name: "Numbers (10.1)"
    - id: "1091189122"
      name: "Bear (1.8.2)"
    - id: "409907375"
      name: "Remote Desktop (3.9.3)"
