---

# Change indexing order and disable some search results

 spotlightPref:
    - "com.apple.spotlight orderedItems -array"

 spotlightIndexItemsDisabled:
    - "enabled=0 name=BOOKMARKS enabled=0 name=CONTACT enabled=0 name=EVENT_TODO enabled=0 name=MENU_CONVERSION enabled=0 name=MENU_DEFINITION enabled=0 name=MENU_EXPRESSION enabled=0 name=MENU_OTHER enabled=0 name=MENU_SPOTLIGHT_SUGGESTIONS enabled=0 name=MENU_WEBSEARCH enabled=0 name=MESSAGES enabled=0 name=MOVIES enabled=0 name=MUSIC enabled=0 name=SOURCE enabled=0 name=SYSTEM_PREFS"

 spotlightItems:
#    - "/usr/bin/mdimport -r ~/Library/Spotlight/Markdown.mdimporter"

 spotlightSudo:
#   - "rm -r /private/var/tmp/mds"
    - "sudo mdutil -a -d -i off"

# Use sudo mdutil -i off '/Volumes/foo' to stop indexing any volume.
    - "defaults write /.Spotlight-V100/VolumeConfiguration Exclusions -array '/Volumes'"
    - "rm -rf /.Spotlight*"

# Load new settings before rebuilding the index
    - "killall mds > /dev/null 2>&1"

# Make sure indexing is enabled for the main volume
    - "mdutil -i on / > /dev/null"

# Rebuild the index from scratch, To see if this is working, runmdimport -L
    - "mdutil -E / > /dev/null"  
