---

 terminalPref:

# Only use UTF-8 in Terminal.app
    - "com.apple.terminal StringEncodings -array 4"

# Enable “focus follows mouse” for Terminal.app and all X11 apps
# i.e. hover over a window and start typing in it without clicking first
    - "com.apple.terminal FocusFollowsMouse -bool true"
    - "org.x.X11 wm_ffm -bool true"

# Enable Secure Keyboard Entry in Terminal.app
# See: https://security.stackexchange.com/a/47786/8918
    - "com.apple.terminal SecureKeyboardEntry -bool true"

# Disable the annoying line marks
    - "com.apple.Terminal ShowLineMarks -int 0"

# Set default terminal
    - "com.apple.Terminal 'Default Window Settings' -string 'Red'"
    - "com.apple.Terminal 'Startup Window Settings' -string 'Red'"