---

 userPreferencesPref:

# Chime When Charging - Play iOS charging sound when MagSafe is connected.
    - "com.apple.PowerChime ChimeOnAllHardware -bool true"

# Disable transparency in the menu bar and elsewhere on Yosemite
#   - "com.apple.universalaccess reduceTransparency -bool true"

# Set highlight color to green
#   - "NSGlobalDomain AppleHighlightColor -string "0.764700 0.976500 0.568600"

# Set sidebar icon size to medium
#   - "NSGlobalDomain NSTableViewDefaultSizeMode -int 2"

# Always show scrollbars `WhenScrolling`, `Automatic` and `Always`
    - "NSGlobalDomain AppleShowScrollBars -string 'Always'"

# Disable the over-the-top focus ring animation
    - "NSGlobalDomain NSUseAnimatedFocusRing -bool false"

# Increase window resize speed for Cocoa applications
    - "NSGlobalDomain NSWindowResizeTime -float 0.001"

# Expand save panel by default
    - "NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true"
    - "NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true"

# Expand print panel by default
    - "NSGlobalDomain PMPrintingExpandedStateForPrint -bool true"
    - "NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true"

# Save to disk (not to iCloud) by default
    - "NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false"

# Automatically quit printer app once the print jobs complete
    - "com.apple.print.PrintingPrefs 'Quit When Finished' -bool true"

# Disable the “Are you sure you want to open this application?” dialog
    - "com.apple.LaunchServices LSQuarantine -bool false"

# Disable Resume system-wide
    - "com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false"

# Disable automatic termination of inactive apps
    - "NSGlobalDomain NSDisableAutomaticTermination -bool true"

# Disable the crash reporter
    - "com.apple.CrashReporter DialogType -string 'none'"

# Set Help Viewer windows to non-floating mode
    - "com.apple.helpviewer DevMode -bool true"

# Disable automatic capitalization as it’s annoying when typing code
    - "NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false"

# Disable smart dashes as they’re annoying when typing code
    - "NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false"

# Disable automatic period substitution as it’s annoying when typing code
    - "NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false"

# Disable smart quotes as they’re annoying when typing code
    - "NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false"

# Disable auto-correct -g
    - "NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false"

# Save screenshots to the desktop
    - "com.apple.screencapture location -string '${HOME}/Desktop'"

# Save screnshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
    - "com.apple.screencapture type -string 'png'"

# Set Default Screenshot Name - Date and time remain unchanged.
    - "com.apple.screencapture name 'Evidence'"

# Disable shadow in screenshots
    - "com.apple.screencapture disable-shadow -bool true"

# Enable subpixel font rendering on non-Apple LCDs https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
    - "NSGlobalDomain AppleFontSmoothing -int 1"

# Enable the debug menu in Address Book
    - "com.apple.addressbook ABShowDebugMenu -bool true"

# Use plain text mode for new TextEdit documents
    - "com.apple.TextEdit RichText -int 0"

# Open and save files as UTF-8 in TextEdit
    - "com.apple.TextEdit PlainTextEncoding -int 4"
    - "com.apple.TextEdit PlainTextEncodingForWrite -int 4"

# Enable the debug menu in Disk Utility
    - "com.apple.DiskUtility DUDebugMenuEnabled -bool true"
    - "com.apple.DiskUtility advanced-image-options -bool true"

# Auto-play videos when opened with QuickTime Player
    - "com.apple.QuickTimePlayerX MGPlayMovieOnOpen -bool true"

# Trackpad: enable tap to click for this user and for the login screen
    - "com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true"
    - "NSGlobalDomain com.apple.mouse.tapBehavior -int 1"

# Disable “natural” (Lion-style) scrolling
    - "NSGlobalDomain com.apple.swipescrolldirection -bool false"

# Increase sound quality for Bluetooth headphones/headsets
#     - "com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

# Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
    - "NSGlobalDomain AppleKeyboardUIMode -int 3"

# Disable press-and-hold for keys instead of favor of key repeat
    - "NSGlobalDomain ApplePressAndHoldEnabled -bool true"

#  keyboard repeat rate
    - "NSGlobalDomain KeyRepeat -int 2"
    - "NSGlobalDomain InitialKeyRepeat -int 25"

 userPreferencesItems:

# Chime When Charging - Play iOS charging sound when MagSafe is connected.
    - "open /System/Library/CoreServices/PowerChime.app"

    - "/usr/bin/defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1"    
# Rename Mac's boot drive to Macintosh HD
    - "diskutil rename / 'Macintosh HD'"
    
 userPreferencesSudo:

 # Enable HiDPI display modes (requires restart)
    - "/usr/bin/defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true"

# Reveal IP address, hostname, and OS version when clicking the clock in the login window
    - "/usr/bin/defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName"

# enable OS X updates to be installed automatically on 10.10.x and later.
    - "/usr/bin/defaults write /Library/Preferences/com.apple.commerce AutoUpdateRestartRequired -bool TRUE"

# Restart automatically if the computer freezes
    - "systemsetup -setrestartfreeze on"

# Disable Sudden Motion Sensor - Leaving this turned on is useless when you're using SSDs.
    - "pmset -a sms 0"

# Show language menu in the top right corner of the boot screen
    - "/usr/bin/defaults write /Library/Preferences/com.apple.loginwindow showInputMenu -bool true"

# Set the timezone; measurement unit and language
    - "systemsetup -settimezone 'America/Montreal'"
    - "/usr/bin/defaults write -g AppleMeasurementUnits -string 'Centimeters'" 

# Stop iTunes from responding to the keyboard media keys
    - "launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null"

# Set a custom wallpaper image. `DefaultDesktop.jpg` is already a symlink, and
# all wallpapers are in `/Library/Desktop Pictures/`. The default is `Wave.jpg`.
#rm -rf ~/Library/Application Support/Dock/desktoppicture.db
#sudo rm -rf /System/Library/CoreServices/DefaultDesktop.jpg
#sudo ln -s /path/to/your/image /System/Library/CoreServices/DefaultDesktop.jpg

