---
# ------------------------------------------------------------
# Prepare Mac according to my opinionated standards
# Modified by: Benoît H. Dicaire
# https://GitHub.com/bhdicaire/macSetup
# ------------------------------------------------------------

 - name: "prepareMac: dump all variables and dictionaries"
   include_tasks: "roles/common/tasks/dumpAllVariables.yml"  
   vars: 
     dDumpFile:   "/tmp/dumpAllVariables (prepareMac).txt" 
   when: debugAnsible 

# ------------------------------------------------------------
#  Ensure directories exist
# ------------------------------------------------------------    
 
 - name: Ensure directories exist
   include_tasks: "manageEnv.yml"
   vars:
     macBackupConfig: false
     macRestoreConfig: false

# ------------------------------------------------------------
# Executes tasks
# ------------------------------------------------------------ 

 - name: prepareMac - activities initialization
   file: path="~//macSetup-PrepareMac.lck" state=touch owner="{{ localUser }}"

 - name: Computer Name Module
   include_tasks: "computerName.yml"
   vars:
     dComputerName: "{{ computerName }}"
   when: computerName is defined
   run_once: true

 - name: Bash v4
   include_tasks:  "{{ playbookPath }}/roles/common/tasks/homeBrew.yml"
   vars:
     dHomeBrewType: "brew"
     dHomeBrewApplication:
       - name: "bash"
   run_once: true

 - name: Enable bash4 in /etc/shells
   command: "echo /usr/local/bin/bash >> /etc/shells"
   become: yes
   run_once: true

 - name: Add groups
   include_tasks: "{{ playbookPath }}/roles/common/tasks/addGroup.yml"
   vars:
    dGroupName: "{{ dAddGroup.name }}"
    dGroupGID: "{{ dAddGroup.gid }}"
   with_items:
    -   "{{ moreGroups }}"
   loop_control:
    loop_var: dAddGroup

 - name: Modify the shell for the current local user
   include_tasks: "{{ playbookPath }}/roles/common/tasks/addUser.yml"
   vars:
     dUserName: "{{ localUser }}"
     dUserComment: "{{ localUserComment | default(omit)}}"
     dUserGroup: "{{ localGroup | default(omit)}}"
     dUserGroups: "{{ localGroups | default(omit)}}"
     dUserShell: "{{ localShell | default(omit)}}"
   when: localUser is defined
   run_once: true    
  
 - name: Add users
   include_tasks: "{{ playbookPath }}/roles/common/tasks/addUser.yml"
   vars:
    dUserName: "{{ dAddUser.name }}"
    dUserComment: "{{ dAddUser.comment | default(omit)}}"
    dUserGroup: "{{ dAddUser.group | default(omit)}}"
    dUserGroups: "{{ dAddUser.groups | default(omit)}}"
    dUserShell: "{{ dAddUser.shell | default(omit)}}"
   with_items:
     -   "{{ moreUsers }}"
   loop_control:
    loop_var: dAddUser

 - name: Install required tools
   include_tasks: "{{ playbookPath }}/roles/common/tasks/homeBrew.yml"
   vars:
     dTap:              "{{ brewTaps }}"
     dApplication:      "{{ dItemApp }}"
     dInstallationType: "brew"
   with_items:
     -   "{{ prepareBrew }}"
   loop_control:
    loop_var: dItemApp     
 - copy:
     src: "{{ item }}"
     dest: ~/bin
     mode: 0744
   with_fileglob: 
     - "{{ playbookPath }}/roles/prepareMac/files/loginItems/loginItem*"

 - name: ensure github.com is a known host
   lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
   run_once: true

######################################################################
###
### Copy prerequisites items
###
######################################################################

# - name: Clone or update required GIT repositories
#   include_tasks: "{{ playbookPath }}/roles/common/tasks/addGitRepo.yml"
#   vars:
#     dGITItem: 
#       src:  "https://github.com/bhdicaire/macSetup.git"
#       dest: "{{ pathPrefix }}{{ macSetupPathSuffix }}"
#     dMkDir: false   
#
# - name: Clone or update required GIT repositories
#   include_tasks: "{{ playbookPath }}/roles/common/tasks/addGitRepo.yml"
#   vars:
#     dGITItem: 
#       src:  "https://github.com/bhdicaire/macSetup.git"
#       dest: "{{ pathPrefix }}{{ macSetupPathSuffix }}"
#     dMkDir: false

 - name: Clone or update required GIT repositories
   include_tasks: "{{ playbookPath }}/roles/common/tasks/addGitRepo.yml"
   vars:
     dGITItem: 
       src:  "{{ dRequiredGitRepo.src }}"
       dest: "{{ dRequiredGitRepo.dest }}"
     dMkDir: false
   with_items:
     - "{{ prepareGIT }}"
   loop_control:
     loop_var: dRequiredGitRepo




 - name: Remove module marker 
   file: path="~/macSetup-PrepareMac.lck" state=absent 
    
 - name: Installation phase 1 is now completed  
   file: path="~/macSetup-PrepareMac (completed)" state=touch owner="{{ localUser }}"      

 -  name: Reboot
    command: "echo -e reboot"
    become: no