---
# ------------------------------------------------------------
# Manage environment AND packages configurations
# Modified by: Benoît H. Dicaire
# https://GitHub.com/bhdicaire/macSetup
# ------------------------------------------------------------

 - name: "manageEnv: dump all variables and dictionaries"
   include_tasks: "roles/common/tasks/dumpAllVariables.yml"  
   vars: 
     dDumpFile:   "/tmp/dumpAllVariables (ManageEnv).txt" 
   when: debugAnsible 

 - name: Ensure target directory exist
   block:
     - include_tasks: "{{ playbookPath }}/roles/common/tasks/mkDir.yml"
       vars:
         dDirPath: "{{ dMake }}"
         dDirGroup: "Staff"
       with_items:
         - "{{ backupPath }}"
         - "{{ backupPath }}BusyCal/"
         - "{{ backupPath }}BusyContact/"
         - "{{ backupPath + dotFilesItems.0.dest }}"
         - "{{ dotFilesLocalGIT }}"
         - "{{ dotFilesPath }}"
         - "{{ gitPath }}"
         - "{{ macSetupLocalGIT }}"
         - "{{ macSetupPath }}"         
         - "{{ secretBackupPath }}"
         - "{{ secretBackupPath + secretConfigurationItems.0.dest }}"
         - "{{ spotlightPath}}"
         - "{{ toolsPath }}"
         - "~/BCK/BusyCal/"
         - "~/BCK/BusyContact/"
         - "~/bin/"         
       loop_control:
         loop_var: dMake
     - include_tasks: "{{ playbookPath }}/roles/common/tasks/mkDir.yml"
       vars:
         dDirPath: "{{ dMake.dest }}"
         dDirGroup: "Staff"
       with_items:
         - "{{ appStoreConfig }}" 
         - "{{ brewCaskConfig }}" 
         - "{{ brewCaskDevConfig }}"
         - "{{ macSoftwareConfig }}"
         - "{{ macSoftwareGIT }}"
         - "{{ macSoftwareURL }}"
         - "{{ macSoftwareDevConfig }}"   
         - "{{ prepareGIT }}"     
         - "{{ secretConfigurationItems }}" 
         - "{{ systemRelatedGITItems }}"
       loop_control:
         loop_var: dMake     

# ------------------------------------------------------------
#  Backup current environment AND packages configurations
# ------------------------------------------------------------

 - name: ManageEnv - Backup activities initialization
   block:
     - file: path="~/macSetup-ManageEnv.lck" state=touch owner="{{ localUser }}"
     - shell: "find ~ -name '.bashrc_*' -maxdepth 1 | grep -v original"
       register: bashRCComponents
       ignore_errors: yes 
   when: macBackupConfig == true
   
 - name: Backup - Copy configuration items
   block: 
     - include_tasks: "{{ playbookPath }}/roles/common/tasks/cpItems.yml"
       vars:
         dCopyItem:
           src:  "{{ item.src }}"
           dest: "{{ item.dest }}"
         dMkDir: false
       with_items:
         - "{{ secretConfigurationItems }}"
         - "{{ dotFilesItems }}"
         - "{{ systemRelatedItems }}"
         - "{{ macSoftwareConfig }}"  
#        - "{{ toolsPath }}"                
     - copy:
         src: "{{ item }}"
         dest: "{{ backupPath }}dotFiles/"
       with_items:
         - '{{ bashRCComponents.stdout_lines }}'  
       ignore_errors: yes   
     - copy:
         src: "{{ item }}"
         dest: "{{ dotFilesLocalGIT }}dot/"
       with_items:
         - '{{ bashRCComponents.stdout_lines }}'  
   when: macBackupConfig == True

 - name: Backup - Copy git repositories
   block: 
     - include_tasks: "{{ playbookPath }}/roles/common/tasks/cpItems.yml"
       vars:
         dCopyItem:
           src:  "{{ dCopy }}"
           dest: "{{ dotFilesLocalGIT }}dot" 
         dMkDir: false
       with_items:
         - "{{ dotFilesItems }}"
     - include_tasks: "{{ playbookPath }}/roles/common/tasks/cpItems.yml"
       vars:
         dCopyItem:
           src:  "{{ item.src }}"
           dest: "{{ item.dest }}"
         dMkDir: false
       with_items:
         - "{{ systemRelatedGITItems }}"
   when: macBackupConfig == true
   
 - name: Remove marker 
   file: path="~/.macSetup-Backup" state=absent owner="{{ localUser }}" 
   when: macBackupConfig == true

# ------------------------------------------------------------
#  Restore environment AND packages configurations
# ------------------------------------------------------------

 - name: ManageEnv - Restore activities initialization 
   file: path="~/.macSetup-Restore" state=touch owner="{{ localUser }}"
   when: macRestoreConfig == True 

 - name: Restore environment AND packages configurations
   block:
     - include_tasks: "{{ playbookPath }}/roles/common/tasks/cpItems.yml"
       vars:
         dMkDir: False
         dCopyItem:
           src: "{{ dSoftware.dest }}{{ dSoftware.suffix }}"
           dest: "{{ dSoftware.src }}"
       with_items:
         - "{{ macSoftwareConfig }}"
         - "{{ appStoreConfig }}"
       loop_control:
         loop_var: dSoftware   
     - name: Copy opiniated bash files
       copy: src='{{ dotFilesPath }}dot/{{ item }}' dest='{{ home }}/.{{ item }}' mode=651
       with_items:
         - "{{ dotFiles }}"         
   when: macRestoreConfig == True

 - name: Remove marker 
   file: path="~/macSetup-ManageEnv.lck" state=absent owner="{{ localUser }}"
   when: macRestoreConfig == True