---

 - homebrew: 
     name: mas
     state: latest
   ignore_errors: yes

 - name: Get MAS account status
   shell: 'mas account'
   register: mas_account_result
   
 - name: List installed MAS apps.
   command: mas list
   register: mas_list
   ignore_errors: yes

 - name: Ensure configured MAS apps are installed.
   command: mas install "{{ item.id }}"
   with_items: "{{ appStore }}"
   ignore_errors: yes
 
 - name: Upgrade all apps (if configured).
   command: mas upgrade

 - name: app store's preferences
   shell: defaults write {{ item }}
   with_items:
     -  "{{ appStorePref }}"