---

    - name: Get MAS account status
      shell: 'mas account'
      register: mas_account_result
      tags: ['setup']
   
    - name: List installed MAS apps.
      command: mas list
      register: mas_list
      tags: ['setup'] 
      
    - name: Ensure configured MAS apps are installed.
      command: mas install "{{ item.id }}"
      with_items: "{{ appStore }}"
      tags: ['setup'] 
      
    - name: Upgrade all apps (if configured).
      command: mas upgrade
      tags: ['setup'] 

   - name: Copy configuration files
     synchronize:
       src: "{{ item.dest }}{{ item.suffix }}"
       dest: "{{ item.src }}"
       compress: no
       rsync_opts:
         - "-aW"
         - "--ignore-missing-args"
     with_items:
       - "{{ appStoreConfig }}"

    - name: app store's preferences
      shell: defaults write {{ item }}
      with_items:
      -  "{{ appStorePref }}"
      tags: ['setup'] 

