---

  - name: Ensure target directory exists
    file:
      path: "{{ item.dest }}"
      state: directory
      owner: "{{ localUser }}"
      group: "{{ localGroup }}" 
      mode: 0750
    with_items:
      - "{{ /tmp/root }}"

   - name: restore configuration files
     synchronize:
       src: "{{ backupPath {{ item.dest }}{{ item.suffix }}"
       dest: "/tmp/root/{{ item.src }}"
       compress: no
       rsync_opts:
         - "-aW"
         - "--ignore-missing-args"
     with_items:
       - "{{ dotFilesItems }}" 
       - "{{ binItems }}" 

