---
   - name: Create required Dropbox subdirectories and then create symbolic links
     file: path='{{ item.src }}' state=directory owner={{ localUser }} group=staff mode=0751
     with_items:
       - "{{ dotLinksItems }}"
  
   - file: src='{{ item.src }}' dest='{{ item.dest }}' state=link
     with_items:
       - "{{ dotLinksItems }}"
     tags: ['dotFiles']