---

 - debug: msg="** macSetup BREW module **"

 - homebrew: update_homebrew=yes upgrade_all=yes

 - name: Install applications with homebrew
   homebrew: update_homebrew=yes upgrade_all=yes

 - shell: brew cleanup

 - homebrew_tap: name="{{ item }}" state=present
   with_items:
   - "{{ brewTaps }}"

 - homebrew: name="{{ item }}" state=present
   with_items:
   - "{{ brew }}"
   tags: ['setup']
 
 - shell: brew cleanup

 - homebrew_cask: name="{{ item }}" path="{{ brew_cask_appdir }}" state=present
   with_items:
   - "{{ brewCask }}"
   tags: ['setup']
 
 - shell: brew cask cleanup
 
     - name: app store's preferences
      shell: defaults write {{ item }}
      with_items:
      -  "{{ macSoftwareConfigPref }}"
      tags: ['setup'] 
      
   - name: Copy configuration files
     synchronize:
       src: "{{ item.dest }}{{ item.suffix }}"
       dest: "{{ item.src }}"
       compress: no
       rsync_opts:
         - "-aW"
         - "--ignore-missing-args"
     with_items:
       - "{{ brewCaskConfig }}" 

   - name: user's preferences configuration
     shell: defaults write {{ item }}
     with_items:
      - "{{ bbeditPref }}"
      - "{{ googleChromePref }}"

   - name: user's preferences items
     command: "{{ item }}"
     with_items:
      - "{{ bbeditItems }}"     



