---
# ------------------------------------------------------------
# deployMac according to my opinionated standards
# Modified by: Benoît H. Dicaire
# https://GitHub.com/bhdicaire/macSetup
# ----------------------------------------------------------

 - name: "deployMac: dump all variables and dictionaries"
   include_tasks: "roles/common/tasks/dumpAllVariables.yml"  
   vars: 
     dDumpFile:   "/tmp/dumpAllVariables (deployMac).txt" 
   when: debugAnsible 
    
 - name: "deployMac: activities initialization"
   file: path="~/.macSetup-DeployMac.lck" state=touch owner="{{ localUser }}"

# ------------------------------------------------------------
# Install softwares
# ------------------------------------------------------------

 - name: Clone or update required GIT repositories
   include_tasks: "{{ playbookPath }}/roles/common/tasks/addGitRepo.yml"
   vars:
     dGITItem: 
       src:  "{{ dRequiredGitRepo.src }}"
       dest: "{{ dRequiredGitRepo.dest }}"
     dMkDir: false
   with_items:
     - "{{ macSoftwareGIT }}"
   loop_control:
     loop_var: dRequiredGitRepo
          
 - name: Install required tools
   include_tasks: "{{ playbookPath }}/roles/common/homeBrew.yml"
   vars:
     dTap:              "{{ brewTaps }}"
     dApplication:      "{{ dItemApp }}"
     dInstallationType: "brew"
   with_items:
   - "{{ brew }}"
   loop_control:
    loop_var: dItemApp  

 - name: Install required tools
   include_tasks: "{{ playbookPath }}/roles/common/homeBrew.yml"
   vars:
     dTap:              "{{ brewTaps }}"
     dApplication:      "{{ dItemApp }}"
     dInstallationType: "cask"
   with_items:
   - "{{ brewCask }}"
   loop_control:
    loop_var: dItemApp      

 - name: Install Mac App Store's Applications
   include_tasks: "appStore.yml"

 - name: Download packages not available via Brew, Cask or the AppleStore
   get_url: url="{{ item.src }}" dest="{{ item.dest }}"
   with_items:
     - "{{ macSoftwareURL }}"
   ignore_errors: yes 
       
 - name: Insert items that will open automaticaly at login
   shell: ~/bin/loginItems -a {{ item }}
   with_items:
     - "{{ loginComponents }}"

 - name: "Customize user's preferences items"
   shell: defaults write {{ item }}
   with_items:
    - "{{ msOfficePref }}"  
    - "{{ bbeditPref }}"
    - "{{ googleChromePref }}"    
    - "{{ macSoftwareConfigPref }}"
    
 - name: "Customize user's preferences items #2"
   command: "{{ item }}"
   with_items:
    - "{{ bbeditItems }}"       
 
 - name: "Customize user's preferences sudo items"
   command: "{{ item }}"
   with_items:
    - "{{ msOfficeSudo }}"
   become: yes
   
 - name: Restore environment and package config
   include_tasks: "manageEnv.yml"
   vars:
     macBackupConfig: false
     macRestoreConfig: true
   when: gougou is defined 
  
 - name: Remove module marker 
   file: path="~/.macSetup-DeployMac.lck" state=touch owner="{{ localUser }}"
    
 -  name: Reboot
    command: "echo -e reboot"
    become: no