---

  

 
 - name: Copy opiniated bash, color palettes, git and services configuration
   file: path='{{ home }}{{ item }}' state=directory owner=bhdicaire group=staff mode=0751
   with_items:
    - "/bin/"
    - "/Dropbox/"
   tags: ['configure']

 - file: path='{{ home }}/.ssh/' state=directory mode=0700
   tags: ['configure']
  
 - copy: src='{{ item.src }}' dest='{{ item.dest }}' mode=651
   with_items:       
     - "{{ dotFilesDir }}"
   tags: ['configure']
   
#  - copy: src='{{ item.src }}' dest='{{ item.dest }}' directory_mode=yes
#    with_items:       
#      - "{{ dotFilesDir }}"
#    tags: ['configure']   



 - name: Insert items that will open autonaticaly at login
   shell: ~/bin/loginitems.sh -a {{ item }}
   with_items:
     - "{{ loginComponents }}"
   become: yes     
   tags: ['setup']

 -  name: Reboot
    command: '{{  item }}'
    with_items:
     - "reboot"
    become: yes
    tags: ['setup'] 
    
    
 
 - name: Copy opiniated bash, color palettes, git and services configuration
   file: path='{{ home }}{{ item }}' state=directory owner=bhdicaire group=staff mode=0751
   with_items:
    - "/bin/"
    - "/Dropbox/"
   tags: ['configure']

 - file: path='{{ home }}/.ssh/' state=directory mode=0700
   tags: ['configure']
  
 - copy: src='{{ item.src }}' dest='{{ item.dest }}' mode=651
   with_items:       
     - "{{ dotFilesDir }}"
   tags: ['configure']
   
#  - copy: src='{{ item.src }}' dest='{{ item.dest }}' directory_mode=yes
#    with_items:       
#      - "{{ dotFilesDir }}"
#    tags: ['configure']   

 - copy: src='{{ dotFilesPath }}dot/{{ item }}' dest='{{ home }}/.{{ item }}' mode=651
   with_items:
    - "{{ dotFiles }}"
   tags: ['configure']