---

# ------------------------------------------------------------
# add hostname
# ------------------------------------------------------------

 - debug:
     msg: "** Create one or several groups **"
     verbosity: 2
 - debug:
     msg: "name: {{ dHost }}"
     verbosity: 2
 - debug:
     msg: "IP: {{ IP | default(omit)}} or 127.0.0.1"
     verbosity: 2



   
 - name: add {{ host }} to /etc/hosts
   lineinfile: 
     dest: "/etc/hosts" 
     regexp: '.*{{ dHost }}$' 
     line: "{{ ip }} {{ dHost | default(bingo)}}$}" 
     state: present
   become: yes 
   when: IP is defined
