---
# ------------------------------------------------------------
# Backup current environment AND packages configurations
# Modified by: Benoît H. Dicaire
# https://GitHub.com/bhdicaire/macSetup
# ------------------------------------------------------------

   - name: Setup marker 
     file: path="~/.macSetup-Backup" state=touch owner="{{ localUser }}"

   - include_vars: 
      dir: "{{ playbookPath }}/roles/{{ item }}/vars"
     with_items:
      - common
      - deployDev
      - deployMac
      - deployServer

# ------------------------------------------------------------
# Update my local backup
# ------------------------------------------------------------

   - include: "{{ playbookPath }}/roles/common/tasks/mkDir.yml"
     vars:
       dFramework: "{{ item }}"
     with_items:
       - "{{ spotlightPath}}"
       - "{{ gitPath }}"
       - "{{ macSetupLocalGIT }}"
       - "{{ dotFilesLocalGIT }}"
       - "{{ toolsPath }}"
       - "{{ backupPath }}"
       - "{{ secretBackupPath }}"
       - "{{ backupPath + dotFilesItems.0.dest }}"
       - "{{ secretBackupPath + secretConfigurationItems.0.dest }}"

   - include: "{{ playbookPath }}/roles/common/tasks/cpItems.yml"
     vars:
       dFramework: "{{ item }}"
       dFrameworkDest: "{{ secretBackupPath }}{{ item.dest }}"
     with_items:
       - "{{ secretConfigurationItems }}"

   - include: "{{ playbookPath }}/roles/common/tasks/cpItems.yml"
     vars:
       dFramework: "{{ item }}"
       dFrameworkDest: "{{ backupPath }}{{ item.dest }}"
     with_items:
       - "{{ dotFilesItems }}"
       - "{{ systemRelatedItems }}"

   - name: Identify BashRC components
     shell: "find ~ -maxdepth 1 -name '.bashrc_*'| grep -v original"
     register: bashRCComponents

   - name: Copy BashRC components
     copy:
       src: "{{ item }}"
       dest: "{{ backupPath }}dotFiles/"
     with_items:
       - '{{ bashRCComponents.stdout_lines }}'

# ------------------------------------------------------------
# Update my git repositories
# ------------------------------------------------------------

   - include: "{{ playbookPath }}/roles/common/tasks/cpItems.yml"
     vars:
       dFramework: "{{ item }}"
       dFrameworkDest: "{{ dotFilesLocalGIT }}dot"
     with_items:
       - "{{ dotFilesItems }}"

   - name: Copy BashRC components
     copy:
       src: "{{ item }}"
       dest: "{{ dotFilesLocalGIT }}dot/"
     with_items:
       - '{{ bashRCComponents.stdout_lines }}'

   - include: "{{ playbookPath }}/roles/common/tasks/cpItems.yml"
     vars:
       dFramework: "{{ item }}"
       dFrameworkDest: "{{ item.dest }}"
     with_items:
       - "{{ systemRelatedGITItems }}"

 # ------------------------------------------------------------
   - name: Remove marker 
     file: path="~/.macSetup-Backup" state=absent owner="{{ localUser }}" 
