---

# ------------------------------------------------------------
# dLibrary cpItems v1.0
# ------------------------------------------------------------

 - block:
     - name: "** dLibrary cpItems version 1.0 **"
       command: /usr/bin/false
   rescue:
     - debug: 
         msg: 'I caught an error in the module initialization'
     - debug: 
         msg: "Source: {{ dCopyItem.src }}"
     - debug: 
         msg: "Destination: {{ dCopyItem.dest }}"
     - debug: 
         msg: "owner: {{ dDirOwner | default(omit)}} or {{ localUser }}"
     - debug: 
         msg: "group: {{ dDirGroup | default(omit)}} or {{ localGroup}}"
     - debug: 
         msg: "mode: {{ dDirMode | default(omit)}} or 0750"
     - debug:
         msg: "Create target directory? {{ dMkDir | default(No)}}"
     - debug:
         msg: "Compress files? {{ dCopyItem.compress | default('No')}}"     
     - debug:
         msg: "RSync options: {{ dCopyItem.options | default('-aW --ignore-missing-args')}}"                 
     - fail:
         msg: "Input variable dDirPath is not defined" 
   when: dCopyItem is not defined


 - name: Ensure target directory exist
   include_tasks: "{{ playbookPath }}/roles/common/tasks/mkDir.yml"
   vars:
     dDirPath: "{{ dMake.dest }}"
   with_items:
     - "{{ dCopyItem }}"
   loop_control:
     loop_var: dMake
   when: dMkDir == True  

 - name: Copy files
   synchronize:
    src: "{{ dItem.src }}"
    dest: "{{ dItem.dest }}"
    compress: "{{ dItem.compress | default('no')}}"
#    rsync_opts:: 
#      - "--no-motd"
#      - "-aW"
#      - "--ignore-missing-args"
   with_items:
     - "{{ dCopyItem }}"
   loop_control:
     loop_var: dItem
   ignore_errors: yes

# ---------------------------------------------------------------------------------------
# RSync options:
#
#  -a is for archive, which preserves ownership & permissions
#  -W is for copying whole files only, without delta-xfer algorithm to reduce CPU load
# --noCompress on local host, bandwith is not an issue
# ---------------------------------------------------------------------------------------