---

# ------------------------------------------------------------
# dLibrary homebrew v1.0
# ------------------------------------------------------------

 - block:
     - name:  "** macSetup homeBrew module **"
       homebrew: update_homebrew=yes upgrade_all=yes
   rescue:
     - debug: 
         msg: 'I caught an error in the module initialization'
   always:
     - name: Brew maintenance
       shell: brew doctor
       shell: brew cleanup
   run_once: true